import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class UniversitiesService {

  getUniversityCoordinates(){
    return [
      [52.356034, 4.955962],
      [51.524639, -0.134138],
      [1.348417, 103.683092]
    ];
  }
  getUniversities() {
    return [
      {name: 'Abu Dhabi University'},
      {name: 'TET Dhabi University'},
      {name: 'Ajman University of Science & Technology'},
      {name: 'Alain University of Science and Technology'},
      {name: 'Al Ghurair University'},
      {name: 'Alhosn University'},
      {name: 'Al Khawarizmi International College'},
      {name: 'American College Of Dubai'},
      {name: 'American University in Dubai'},
      {name: 'American University in the Emirates'},
      {name: 'American University of Sharjah'},
      {name: 'British University in Dubai'},
      {name: 'Dubai Medical College for Girls'},
      {name: 'Dubai Pharmacy College'},
      {name: 'Etisalat University College'},
      {name: 'Gulf Medical University'},
      {name: 'Hamdan Bin Mohammed e-University'},
      {name: 'Higher Colleges of Technology'},
      {name: 'Ittihad University'},
      {name: 'Jumeira University'},
      {name: 'Khalifa University'},
      {name: 'Khalifa University of Science, Technology and Research'},
      {name: 'Masdar University Of Science And Technology'},
      {name: 'New York University, Abu Dhabi'},
      {name: 'Paris-Sorbonne University Abu Dhabi'},
      {name: 'Rak Medical & Health Sciences University'},
      {name: 'Rochester Institute of Technology, Dubai'},
      {name: 'Skyline University College, Sharjah'},
      {name: 'Synergy University, Dubai Campus'},
      {name: 'The Emirates Academy of Hotel Managment'},
      {name: 'The Petroleum Institute'},
      {name: 'United Arab Emirates University'},
      {name: 'University Of Dubai'},
      {name: 'University of Jazeera'},
      {name: 'University of Sharjah'},
      {name: 'University of Wollongong - Dubai Campus'},
      {name: 'Zayed University'},
      {name: 'Afghan University'},
      {name: 'Al-Birony University'},
      {name: 'American University of Afghanistan'},
      {name: 'Aria Institute of Higher Education'},
      {name: 'Badakhshan University'},
      {name: 'Baghlan University'},
      {name: 'Bakhtar University'},
      {name: 'Balkh University'},
      {name: 'Bamiyan University'},
      {name: 'Bost University'},
      {name: 'Dawat University'},
      {name: 'Dunya Institute of Higher Education'},
      {name: 'Faryab Higher Education Institute'},
      {name: 'Ghazni University'},
      {name: 'Herat University'},
      {name: 'Ibn Sina University'},
      {name: 'Jawzjan University'},
      {name: 'Kaboora Institute of Higher Education'},
      {name: 'Kabul Education University'},
      {name: 'Kabul Health Sciences Institute'},
      {name: 'Kabul Medical University'},
      {name: 'Kabul University'},
      {name: 'Kandahar University'},
      {name: 'Kardan University'},
      {name: 'Karwan Institute of Higher Education'},
      {name: 'Kateb Institute of Higher Education'},
      {name: 'Khana-e-Noor Institute of Higher Education'},
      {name: 'Khurasan University'},
      {name: 'Maryam Institute of Higher Education'},
      {name: 'Nangarhar University'},
      {name: 'National Military Academy of Afghanistan'},
      {name: 'Paktia University'},
      {name: 'Pamir University'},
      {name: 'Parwan University'},
      {name: 'Polytechnical University of Kabul'},
      {name: 'Rana Institute of Higher Education'},
      {name: 'Sadat Institute of Higher Education'},
      {name: 'Salam University'},
      {name: 'Shaikh Zayed University'},
      {name: 'Taj Institute of Higher Education'},
      {name: 'Takhar University'},
      {name: 'American University of Antigua'},
      {name: 'University of Health Sciences Antigua'},
      {name: 'Academy of Arts'},
      {name: 'Academy of Sports and Physical Training'},
      {name: 'Agricultural University of Tirane'},
      {name: 'American University of Tirana'},
      {name: 'Beder University'},
      {name: 'Epoka University'},
      {name: 'Polytechnic University of Tirane'},
      {name: 'University of Elbasan Aleksander Xhuvani'},
      {name: 'University of Gjirokstra Eqerem Cabej'},
      {name: 'University of Korca Fan Noli'},
      {name: 'University of New York Tirana'},
      {name: 'University of Shkodra Luigj Gurakuqi'},
      {name: 'University of Tirana'},
      {name: 'University of Vlora Ismail Qemali'},
      {name: 'University “Pavaresia” Vlore'},
      {name: 'American University of Armenia'},
      {name: 'Armenian State Agrarian University'},
      {name: 'Armenian State University of Economics'},
      {name: 'Eurasia International University'},
      {name: 'European Regional Educational Academy of Armenia'},
      {name: 'French University in Armenia (UFAR)'},
      {name: 'Mehrabyan Medical Institute and Medical College'},
      {name: 'Russian-Armenian (Slavonic) State University'},
      {name: 'State Engineering University of Armenia'},
      {name: 'Yerevan Haibusak University'},
      {name: 'Yerevan State Medical University'},
      {name: 'Yerevan State University'},
      {name: 'American University of the Caribbean, Sint Maarten'},
      {name: 'International University School of Medicine (IUSOM)'},
      {name: 'St.Jamess School of Medicine, Bonaire'},
      {name: 'University of Sint Eustatius School of Medicine'},
      {name: 'University of the Netherlands Antilles, Curacao'},
      {name: 'Universidade Católica de Angola'},
      {name: 'Universidade Gregorio Semedo'},
      {name: 'Universidade Independente de Angola'},
      {name: 'Universidade Lusíada de Angola'},
      {name: 'Universidade Metodista de Angola'},
      {name: 'Universidade Metropolitana de Angola'},
      {name: 'Universidade Tecnica de Angola'},
      {name: 'Univesidade Agostinho Neto'},
      {name: 'Instituto de Enseñanza Superior del Ejército'},
      {name: 'Instituto Nacional de Educación Física General Manuel Belgrano'},
      {name: 'Instituto Tecnológico de Buenos Aires'},
      {name: 'Instituto Universitario Aeronáutico'},
      {name: 'Instituto Universitario CEMA'},
      {name: 'Instituto Universitario de Ciencias de la Salud Fundación H.A. Barceló'},
      {name: 'Instituto Universitario de Estudios Navales y Marítimos'},
      {name: 'Instituto Universitario de la Policia Federal'},
      {name: 'Instituto Universitario Nacional del Arte'},
      {name: 'Universidad Abierta Interamericana'},
      {name: 'Universidad Adventista del Plata'},
      {name: 'Universidad Argentina de la Empresa'},
      {name: 'Universidad Argentina John F. Kennedy'},
      {name: 'Universidad Atlantida Argentina'},
      {name: 'Universidad Austral Buenos Aires'},
      {name: 'Universidad Autónoma de Entre Ríos'},
      {name: 'Universidad Blas Pascal'},
      {name: 'Universidad CAECE, Buenos Aires'},
      {name: 'Universidad Católica Argentina Santa Maria de los Buenos Aires'},
      {name: 'Universidad Católica de Córdoba'},
      {name: 'Universidad Católica de Cuyo'},
      {name: 'Universidad Católica de La Plata'},
      {name: 'Universidad Católica de Salta'},
      {name: 'Universidad Católica de Santa Fé'},
      {name: 'Universidad Católica de Santiago del Estero'},
      {name: 'Universidad Champagnat'},
      {name: 'Universidad de Belgrano'},
      {name: 'Universidad de Bologna - Representación en Buenos Aires'},
      {name: 'Universidad de Buenos Aires'},
      {name: 'Universidad de Ciencias Empresariales y Sociales'},
      {name: 'Universidad de Concepción del Uruguay'},
      {name: 'Universidad de Congreso'},
      {name: 'Universidad de Flores - Buenos Aires'},
      {name: 'Universidad del Aconcagua'},
      {name: 'Universidad de la Cuenca del Plata'},
      {name: 'Universidad de la Fraternidad de Agrupaciones Santo Tomas de Aquino (FASTA)'},
      {name: 'Universidad de la Marina Mercante'},
      {name: 'Universidad del Centro Educativo Latinoamericano Rosario'},
      {name: 'Universidad del Cine - Buenos Aires'},
      {name: 'Universidad del Museo Social Argentino'},
      {name: 'Universidad del Norte Santo Tomás de Aquino'},
      {name: 'Universidad del Salvador'},
      {name: 'Universidad de Mendoza'},
      {name: 'Universidad de Morón'},
      {name: 'Universidad de Palermo'},
      {name: 'Universidad de San Andres'},
      {name: 'Universidad Empresarial Siglio 21'},
      {name: 'Universidad ISALUD'},
      {name: 'Universidad Juan Agustín Maza'},
      {name: 'Universidad Maimónides'},
      {name: 'Universidad Nacional de Catamarca'},
      {name: 'Universidad Nacional de Córdoba'},
      {name: 'Universidad Nacional de Cuyo'},
      {name: 'Universidad Nacional de Entre Ríos'},
      {name: 'Universidad Nacional de Formosa'},
      {name: 'Universidad Nacional de General San Martín'},
      {name: 'Universidad Nacional de General Sarmiento'},
      {name: 'Universidad Nacional de Jujuy'},
      {name: 'Universidad Nacional de La Matanza'},
      {name: 'Universidad Nacional de Lanus'},
      {name: 'Universidad Nacional de La Pampa'},
      {name: 'Universidad Nacional de la Patagonia Austral'},
      {name: 'Universidad Nacional de la Patagonia San Juan Bosco'},
      {name: 'Universidad Nacional de La Plata'},
      {name: 'Universidad Nacional de La Rioja'},
      {name: 'Universidad Nacional del Centro de la Provincia de Buenos Aires'},
      {name: 'Universidad Nacional del Comahue'},
      {name: 'Universidad Nacional del Littoral'},
      {name: 'Universidad Nacional del Nordeste'},
      {name: 'Universidad Nacional del Noroeste de la Provincia de Buenos Aires'},
      {name: 'Universidad Nacional de Lomas de Zamora'},
      {name: 'Universidad Nacional del Sur'},
      {name: 'Universidad Nacional de Luján'},
      {name: 'Universidad Nacional de Mar del Plata'},
      {name: 'Universidad Nacional de Misiones'},
      {name: 'Universidad Nacional de Quilmes'},
      {name: 'Universidad Nacional de Río Cuarto'},
      {name: 'Universidad Nacional de Rosario'},
      {name: 'Universidad Nacional de Salta'},
      {name: 'Universidad Nacional de San Juan'},
      {name: 'Universidad Nacional de San Luis'},
      {name: 'Universidad Nacional de Santiago del Estero'},
      {name: 'Universidad Nacional de Tres de Febrero'},
      {name: 'Universidad Nacional de Tucumán'},
      {name: 'Universidad Nacional de Villa María'},
      {name: 'Universidad Notarial Argentina'},
      {name: 'Universidad Tecnológica Nacional'},
      {name: 'Universidad Torcuato di Tella'},
      {name: 'Akademie der bildenden Künste Wien'},
      {name: 'Donau-Universität Krems'},
      {name: 'Fachhochschule Burgenland'},
      {name: 'Fachhochschule für Bank- und Finanzwirtschaft'},
      {name: 'Fachhochschule JOANNEUM'},
      {name: 'Fachhochschule Kärnten'},
      {name: 'Fachhochschule Krems'},
      {name: 'Fachhochschule Kufstein (Tirol)'},
      {name: 'Fachhochschule Salzburg'},
      {name: 'Fachhochschule St. Pölten'},
      {name: 'Fachhochschule Vorarlberg'},
      {name: 'Fachhochschule Wiener Neustadt'},
      {name: 'Fachhochschulstudiengänge der Wiener Wirtschaft'},
      {name: 'Fachhochschulstudiengänge Hagenberg'},
      {name: 'Fachhochschulstudiengänge Krems IMC'},
      {name: 'Fachhochschulstudiengänge Steyr'},
      {name: 'Fachhochschulstudiengänge Wels'},
      {name: 'Institute of Science and Technology'},
      {name: 'Katholisch-Theologische Privatuniversität Linz'},
      {name: 'MCI-Management Center Innsbruck'},
      {name: 'Medizinische Universität Graz'},
      {name: 'Medizinische Universität Innsbruck'},
      {name: 'Medizinische Universität Wien'},
      {name: 'Montanuniversität Leoben'},
      {name: 'Private Universität für Medizinische Informatik und Technik Tirol'},
      {name: 'Technikum Wien'},
      {name: 'Technische Universität Graz'},
      {name: 'Technische Universität Wien'},
      {name: 'Universität für angewandte Kunst Wien'},
      {name: 'Universität für Bodenkultur Wien'},
      {name: 'Universität für künstlerische und industrielle Gestaltung Linz'},
      {name: 'Universität für Musik und darstellende Kunst Graz'},
      {name: 'Universität für Musik und darstellende Kunst  Wien'},
      {name: 'Universität Graz'},
      {name: 'Universität Innsbruck'},
      {name: 'Universität Klagenfurt'},
      {name: 'Universität Linz'},
      {name: 'Universität Mozarteum Salzburg'},
      {name: 'Universität Salzburg'},
      {name: 'Universität Vienna'},
      {name: 'Veterinärmedizinische Universität Wien'},
      {name: 'Webster University, Vienna'},
      {name: 'Wirtschaftsuniversität Wien'},
      {name: 'Australian Catholic University'},
      {name: 'Australian Correspondence Schools'},
      {name: 'Australian Defence Force Academy'},
      {name: 'Australian Lutheran College'},
      {name: 'Australian Maritime College'},
      {name: 'Australian National University'},
      {name: 'Avondale College'},
      {name: 'Batchelor Institute of Indigenous Tertiary Education'},
      {name: 'Blue Mountains Hotel School'},
      {name: 'Bond University'},
      {name: 'Central Queensland University'},
      {name: 'Charles Darwin University'},
      {name: 'Charles Sturt University'},
      {name: 'Curtin University of Technology'},
      {name: 'Deakin University'},
      {name: 'Edith Cowan University'},
      {name: 'Flinders University of South Australia'},
      {name: 'Griffith University'},
      {name: 'Holmes Institute'},
      {name: 'Institute Of Technology, Australia'},
      {name: 'International College of Tourism and Hotel Management'},
      {name: 'James Cook University of North Queensland'},
      {name: 'La Trobe University'},
      {name: 'Macquarie University'},
      {name: 'Marcus Oldham College'},
      {name: 'Monash University'},
      {name: 'Murdoch University'},
      {name: 'Queensland University of Technology'},
      {name: 'Royal Melbourne Institute of Technology'},
      {name: 'Southern Cross University'},
      {name: 'Swinburne University of Technology'},
      {name: 'University of Adelaide'},
      {name: 'University of Ballarat'},
      {name: 'University of Canberra'},
      {name: 'University of Divinity'},
      {name: 'University of Melbourne'},
      {name: 'University of Newcastle'},
      {name: 'University of New England'},
      {name: 'University of New South Wales'},
      {name: 'University of Notre Dame Australia'},
      {name: 'University of Queensland'},
      {name: 'University of South Australia'},
      {name: 'University of Southern Queensland'},
      {name: 'University of Sydney'},
      {name: 'University of Tasmania'},
      {name: 'University of Technology Sydney'},
      {name: 'University of the Sunshine Coast'},
      {name: 'University of Western Australia'},
      {name: 'University of Western Sydney'},
      {name: 'University of Wollongong'},
      {name: 'Academy of Public Administration'},
      {name: 'Azerbaijan Diplomatic Academy'},
      {name: 'Azerbaijan International University'},
      {name: 'Azerbaijan Medical University'},
      {name: 'Azerbaijan National Conservatorie'},
      {name: 'Azerbaijan State Economic University'},
      {name: 'Azerbaijan State Oil Academy'},
      {name: 'Azerbaijan Technical University'},
      {name: 'Azerbaijan Technology University'},
      {name: 'Azerbaijan Toursim Institute'},
      {name: 'Azerbaijan University'},
      {name: 'Azerbaijan University ol Languages'},
      {name: 'Baki Business University'},
      {name: 'Baku Slavic University'},
      {name: 'Baku State University'},
      {name: 'Ganja State University '},
      {name: 'Khazar University'},
      {name: 'Lankaran State University'},
      {name: 'Nakhchivan Private University'},
      {name: 'Nakhchivan State University'},
      {name: 'National Aviation Academy'},
      {name: 'Odlar Yurdu University'},
      {name: 'Police Academy'},
      {name: 'Qafqaz University'},
      {name: 'Sumgait State University'},
      {name: 'Western University'},
      {name: 'American University'},
      {name: 'International Burch University'},
      {name: 'International University of Sarajevo'},
      {name: 'International University of Travnik'},
      {name: 'Sarajevo Film Academy'},
      {name: 'Slobomir P Univerzitet'},
      {name: 'University of Banja Luka'},
      {name: 'University of Bihac'},
      {name: 'University of East Srarajevo'},
      {name: 'University of Mostar'},
      {name: 'University of Sarajevo'},
      {name: 'University of Tuzla'},
      {name: 'University of Zenica'},
      {name: 'University Vitez In Travnik'},
      {name: 'Univerzitet u Mostaru Dzemal Bijedic'},
      {name: 'University of the West Indies, Cave Hill'},
      {name: 'Ahsanullah University of Science & Technology'},
      {name: 'American International University - Bangladesh'},
      {name: 'Asa University Bangladesh'},
      {name: 'Asian University of Bangladesh'},
      {name: 'Atish Dipankar University'},
      {name: 'Bangabandhu Sheikh Mujibur Rahman Agricultural University'},
      {name: 'Bangabandhu Sheikh Mujibur Rahman Medical University'},
      {name: 'Bangladesh Agricultural University'},
      {name: 'Bangladesh Open University'},
      {name: 'Bangladesh University'},
      {name: 'Bangladesh University of Business & Technology'},
      {name: 'Bangladesh University of Engineering and Technology'},
      {name: 'Bangladesh University of Professionals'},
      {name: 'Bangladesh University of Textiles'},
      {name: 'Begum Rokeya University, Rangpur'},
      {name: 'BGC Trust University, Bangladesh'},
      {name: 'Brac University'},
      {name: 'Chittagong Independent University'},
      {name: 'Chittagong University of Engineering and Technology'},
      {name: 'City University'},
      {name: 'Comilla University'},
      {name: 'Daffodil International University'},
      {name: 'Darul Ihsan University'},
      {name: 'Dhaka International University'},
      {name: 'Dhaka University of Engineering and Technology'},
      {name: 'East Delta University'},
      {name: 'Eastern University'},
      {name: 'East West University'},
      {name: 'East-West University, Mohakhali'},
      {name: 'Green University of Bangladesh'},
      {name: 'Hajee Mohammad Danesh Science and Technology University'},
      {name: 'IBAIS University'},
      {name: 'Independent University, Bangladesh'},
      {name: 'International Culture University '},
      {name: 'International Islamic University Chittagong'},
      {name: 'International University of Business Agriculture and Technology'},
      {name: 'Islamic University Kushtia'},
      {name: 'Islamic University of Technology'},
      {name: 'Jagannath University'},
      {name: 'Jahangirnagar University'},
      {name: 'Jatiya Kabi Kazi Nazrul Islam University'},
      {name: 'Khulna University'},
      {name: 'Khulna University of Engineering And Technology'},
      {name: 'Leading University'},
      {name: 'Manarat International University'},
      {name: 'Mawlana Bhashani Science And Technology University'},
      {name: 'Metropolitan University'},
      {name: 'Military Institute of Science and Technology'},
      {name: 'National University'},
      {name: 'Noakhali University of Science and Technology'},
      {name: 'North East University Banglades'}]
  }
}
